import React, { useState, useEffect, useCallback } from "react";
import "./App.css";

/**
 * This frontend React app displays live cricket commentary, interactive fan polls (generated by AI backend),
 * collects/votes on polls, and shows poll results in real-time. It features a vibrant, sports-themed UI.
 *
 * Main UI sections:
 * - Header: Match info
 * - Live commentary feed (auto-refreshes)
 * - Polls: vote/see results live
 * - Footer: credits/info
 */

// Backend endpoint roots (replace with env vars/config in prod)
const API_BASE = process.env.REACT_APP_API_BASE || "http://localhost:5000/api";

// Styling theme constants for sports/vibrant look
const PRIMARY = "#1976d2"; // Deep Blue
const ACCENT = "#ff9800"; // Orange
const SECONDARY = "#e3f2fd"; // Pale Blue

// PUBLIC_INTERFACE
function App() {
  const [theme, setTheme] = useState("light");
  const [matchInfo, setMatchInfo] = useState({
    teams: "IND vs AUS",
    venue: "Wankhede Stadium, Mumbai",
    status: "1st ODI - Live",
  });
  const [commentary, setCommentary] = useState([]);
  const [poll, setPoll] = useState(null);
  const [pollResults, setPollResults] = useState(null);
  const [selectedOption, setSelectedOption] = useState(null);
  const [voteStatus, setVoteStatus] = useState({ loading: false, voted: false, error: null });

  // PUBLIC_INTERFACE
  const toggleTheme = () => {
    setTheme((prev) => (prev === "light" ? "dark" : "light"));
  };

  // Fetch live commentary from backend
  const fetchCommentary = useCallback(async () => {
    try {
      const res = await fetch(`${API_BASE}/commentary`);
      const data = await res.json();
      setCommentary(Array.isArray(data) ? data : []);
    } catch (e) {
      setCommentary([]);
    }
  }, []);

  // Fetch current poll from backend
  const fetchPoll = useCallback(async () => {
    try {
      const res = await fetch(`${API_BASE}/poll/active`);
      if (!res.ok) {
        setPoll(null);
        return;
      }
      const data = await res.json();
      setPoll(data);
    } catch {
      setPoll(null);
    }
  }, []);

  // Fetch poll results (after voting or periodically)
  const fetchPollResults = useCallback(async (pollId) => {
    try {
      if (!pollId) return;
      const res = await fetch(`${API_BASE}/poll/${pollId}/results`);
      if (!res.ok) {
        setPollResults(null);
        return;
      }
      const data = await res.json();
      setPollResults(data);
    } catch {
      setPollResults(null);
    }
  }, []);

  // On mount: theme, poll, commentary fetch interval
  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
  }, [theme]);

  // Commentary poller (every 6 seconds)
  useEffect(() => {
    fetchCommentary();
    const interval = setInterval(fetchCommentary, 6000);
    return () => clearInterval(interval);
  }, [fetchCommentary]);

  // Poll poller (every 10 seconds)
  useEffect(() => {
    fetchPoll();
    const interval = setInterval(fetchPoll, 10000);
    return () => clearInterval(interval);
  }, [fetchPoll]);

  // When poll changes, fetch its results
  useEffect(() => {
    if (poll && poll.id) {
      fetchPollResults(poll.id);
      // Poll result updater
      const interval = setInterval(() => fetchPollResults(poll.id), 8000);
      return () => clearInterval(interval);
    }
    setPollResults(null);
  }, [poll, fetchPollResults]);

  // PUBLIC_INTERFACE
  const handleVote = async () => {
    if (!poll?.id || selectedOption == null) return;
    setVoteStatus({ ...voteStatus, loading: true, error: null });
    try {
      const res = await fetch(`${API_BASE}/poll/${poll.id}/vote`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ option: selectedOption }),
      });
      if (!res.ok) throw new Error("Vote failed");
      setVoteStatus({ ...voteStatus, loading: false, voted: true, error: null });
      // Refetch poll result after voting
      fetchPollResults(poll.id);
    } catch (e) {
      setVoteStatus({ ...voteStatus, loading: false, voted: false, error: "Vote failed. Try again." });
    }
  };

  // --- UI COMPONENTS ---

  // Header with match info
  function Header() {
    return (
      <header style={{
        background: `linear-gradient(90deg, ${PRIMARY} 70%, ${ACCENT} 100%)`,
        color: "#fff",
        padding: "1.5rem",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        borderBottom: `4px solid ${ACCENT}`,
      }}>
        <div style={{ display: "flex", gap: "1rem", alignItems: "center" }}>
          <img
            src="https://img.icons8.com/color/48/000000/cricket.png"
            alt="Cricket"
            style={{ width: 40, height: 40 }}
          />
          <div>
            <div style={{ fontSize: "1.6rem", fontWeight: 600, letterSpacing: "0.04em" }}>{matchInfo.teams}</div>
            <div style={{ fontSize: "1rem", opacity: 0.85 }}>{matchInfo.venue}</div>
          </div>
        </div>
        <div style={{ fontSize: "1.1rem", background: ACCENT, color: "#fff", padding: "0.5em 1em", borderRadius: 10 }}>
          {matchInfo.status}
        </div>
        <button
          className="theme-toggle"
          onClick={toggleTheme}
          aria-label={`Switch to ${theme === "light" ? "dark" : "light"} mode`}
        >
          {theme === "light" ? "🌙 Dark" : "☀️ Light"}
        </button>
      </header>
    );
  }

  // Commentary feed
  function CommentaryFeed() {
    return (
      <section style={{
        background: SECONDARY,
        padding: "1rem 0.5rem",
        borderRadius: 10,
        margin: "1.2rem auto",
        width: "98%",
        maxWidth: 700,
        boxShadow: "0 2px 10px 0 rgba(25, 118, 210, 0.11)",
      }}>
        <h2 style={{ color: PRIMARY, textAlign: "left", marginLeft: 10, marginBottom: 8, fontWeight: 500, fontSize: "1.2rem" }}>
          🏏 Live Commentary
        </h2>
        <div style={{ maxHeight: 150, overflowY: "auto", background: "#fff", borderRadius: 7, padding: "8px 12px" }}>
          {commentary && commentary.length > 0 ? (
            commentary.slice(-8).reverse().map((item, idx) =>
              <div
                key={idx}
                style={{
                  fontSize: "1rem",
                  color: "#282c34",
                  padding: "6px 0",
                  borderBottom: idx !== commentary.length - 1 ? "1px solid #e9ecef" : "none",
                }}
              >{item.text || item}</div>
            )
          ) : (
            <div style={{ color: "#888", fontStyle: "italic" }}>No commentary available.</div>
          )}
        </div>
      </section>
    );
  }

  // Poll UI
  function PollBox() {
    if (!poll) return (
      <div style={{ color: "#777", textAlign: "center", marginTop: "2rem" }}>
        <em>No live poll right now. Stay tuned!</em>
      </div>
    );
    const pollId = poll.id;
    const hasVoted = voteStatus.voted;
    const showResults = hasVoted || (pollResults && pollResults.choices);

    return (
      <section style={{
        margin: "1.2rem auto",
        width: "98%",
        maxWidth: 650,
        background: "#fff",
        borderRadius: 12,
        border: `2px solid ${PRIMARY}`,
        boxShadow: "0 3px 16px 0 rgba(255,152,0,0.07)"
      }}>
        <div style={{ padding: "1.2rem 1rem" }}>
          <h2 style={{
            color: ACCENT,
            fontSize: "1.1rem",
            fontWeight: 700,
            textAlign: "left",
            marginBottom: 10
          }}>
            🎉 Fan Poll:
          </h2>
          <div style={{ fontWeight: 600, marginBottom: 8, color: PRIMARY }}>{poll.question}</div>
          {!showResults ? (
            <form onSubmit={e => { e.preventDefault(); handleVote(); }} style={{ display: "flex", flexDirection: "column", gap: "12px", marginTop: "0.5rem" }}>
              {poll.options.map((option, idx) => (
                <label
                  key={idx}
                  htmlFor={`pollopt${idx}`}
                  style={{
                    background: selectedOption === idx ? ACCENT : "#f5f5f5",
                    color: selectedOption === idx ? "#fff" : "#333",
                    fontWeight: 500,
                    padding: "10px 1em",
                    borderRadius: 9,
                    cursor: "pointer",
                    border: `2px solid ${selectedOption === idx ? ACCENT : "#e0e0e0"}`,
                    transition: "all 0.2s",
                    display: "flex",
                    alignItems: "center"
                  }}
                >
                  <input
                    type="radio"
                    id={`pollopt${idx}`}
                    name="poll"
                    value={idx}
                    checked={selectedOption === idx}
                    onChange={() => setSelectedOption(idx)}
                    style={{ marginRight: 12, accentColor: ACCENT }}
                  />
                  {option}
                </label>
              ))}
              <button
                type="submit"
                disabled={voteStatus.loading || selectedOption == null}
                style={{
                  marginTop: "8px",
                  padding: "12px",
                  fontWeight: 700,
                  fontSize: "1rem",
                  border: "none",
                  borderRadius: 7,
                  background: voteStatus.loading ? "#aaa" : PRIMARY,
                  color: "#fff",
                  boxShadow: "0 2px 8px rgba(25, 118, 210, 0.10)",
                  cursor: voteStatus.loading ? "not-allowed" : "pointer",
                  transition: "background 0.18s"
                }}
                aria-busy={voteStatus.loading}
              >
                {voteStatus.loading ? "Voting..." : "Vote"}
              </button>
              {voteStatus.error && (
                <div style={{ color: "red", fontWeight: 500, marginTop: "0.4em" }}>{voteStatus.error}</div>
              )}
            </form>
          ) : (
            // Show results (bar chart)
            <div style={{ marginTop: "1em" }}>
              <div style={{ fontWeight: 600, color: PRIMARY, marginBottom: 8 }}>Live Poll Results</div>
              {pollResults && pollResults.choices ? (
                <div>
                  {pollResults.choices.map((opt, idx) => {
                    const votes = opt.votes || 0;
                    const pct = pollResults.totalVotes ? Math.round(100 * votes / pollResults.totalVotes) : 0;
                    return (
                      <div key={idx} style={{ margin: "8px 0" }}>
                        <div style={{ display: "flex", alignItems: "center", marginBottom: "2px" }}>
                          <span style={{ minWidth: 30, color: ACCENT, fontWeight: 700 }}>{pct}%</span>
                          <span style={{ marginLeft: 8, flex: 1 }}>{poll.options[idx]}</span>
                        </div>
                        <div style={{
                          background: "#e4e4e4",
                          borderRadius: 6,
                          overflow: "hidden",
                          height: 18
                        }}>
                          <div style={{
                            background: PRIMARY,
                            width: `${pct}%`,
                            height: "100%",
                            transition: "width 0.6s"
                          }} />
                        </div>
                        <span style={{ fontSize: "0.95em", color: "#627891", marginLeft: 4 }}>
                          {votes} vote{votes !== 1 ? "s" : ""}
                        </span>
                      </div>
                    );
                  })}
                  <div style={{ fontWeight: 500, color: "#555", marginTop: 15 }}>
                    <span role="img" aria-label="Trophy">🏆</span> Total Votes: <strong>{pollResults.totalVotes}</strong>
                  </div>
                </div>
              ) : (
                <div style={{ color: "#888", fontStyle: "italic", margin: "1em 0" }}>No votes yet.</div>
              )}
            </div>
          )}
        </div>
      </section>
    );
  }

  // Footer UI
  function Footer() {
    return (
      <footer style={{
        background: "#212121",
        color: "#fff",
        textAlign: "center",
        padding: "1em 0",
        marginTop: "2rem",
        fontSize: "0.96rem"
      }}>
        Powered by <span style={{ color: ACCENT, fontWeight: 600 }}>CricketPulse AI</span> | {" "}
        <a href="https://icons8.com/icon/7gO8WmyhynZp/cricket" target="_blank" rel="noopener noreferrer" style={{
          color: PRIMARY,
          textDecoration: "underline"
        }}>Cricket icon by Icons8</a>
      </footer>
    );
  }

  return (
    <div className="App" style={{
      background: theme === "light" ? "#e3f2fd" : "#191a33",
      minHeight: "100vh",
      display: "flex",
      flexDirection: "column"
    }}>
      <Header />
      <main style={{
        flex: 1,
        maxWidth: 860,
        margin: "0 auto",
        width: "100%",
        padding: "1rem 0 0 0",
        background: "none"
      }}>
        <CommentaryFeed />
        <PollBox />
      </main>
      <Footer />
    </div>
  );
}

export default App;
